apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
      access_log	/var/log/nginx/access.log main;
      server {
          listen       80;
          server_name  _;
          location / {
              return 200 "Hello World! - Admiral!!";

          }
      }
    }
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: greeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: greeting
        identity: greeting
    spec:
      containers:
        - image: nginx
          name: greeting
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-conf
              readOnly: true
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-conf
          name: nginx-conf
        - emptyDir: {}
          name: log
  strategy:
    # ----- Everything above this comment are the same as a deployment -----
    canary: # A new field that used to provide configurable options for a Canary strategy
      steps:
        - setWeight: 50
        - pause: {}
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary
  labels:
    app: greeting
    identity: greeting
  namespace: sample
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: greeting