---
apiVersion: admiral.io/v1alpha1
kind: Dependency
metadata:
  name: dependency
  namespace: admiral
spec:
  source: webapp
  #TODO this value is hard coded to identity
  identityLabel: identity
  destinations:
    - greeting
---